[package]
name = "forest_server_discord_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
lnk = "0.5.1"
poise = { version = "0.6", features = ["cache"] }
screenshots = "0.8.2"
sysinfo = "0.29.8"
system_shutdown = "4.0.1"
tokio = { version = "1.32.0", features = ["macros", "signal", "rt-multi-thread"] }
tracing = "0.1.23"
tracing-subscriber = "0.2"
zip-extract = "0.1.2"
